### ISSUE TITLE
TC10 adaption of pom.xml

### ISSUE THREAD

**Issue by codeheap** [JetBrains/teamcity-caches-cleanup-plugin#1]
Hi,

I had some issues on the dependencies when building the project. Maven could not resolve them. And they were still on TC9 libs. Not the TC10 libs. I've modified the pom and now it "mvn package" is working.

Here is my modified pom. I couldn't make a branch or pull request, because I'm wasnt allowed to.

Greetings from Switzerland

caches-cleanup-plugin.pom

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>github.nskvortsov</groupId>
  <artifactId>caches-cleanup-plugin</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <properties>
    <kotlin.version>1.0.3</kotlin.version>
    <teamcity-version>10.0</teamcity-version>
  </properties>
  <repositories>
    <repository>
      <id>JetBrains</id>
      <url>http://download.jetbrains.com/teamcity-repository/</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>JetBrains</id>
      <url>http://download.jetbrains.com/teamcity-repository/</url>
    </pluginRepository>
  </pluginRepositories>
  <build>
    <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
    <testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
    <plugins>
      <plugin>
        <artifactId>kotlin-maven-plugin</artifactId>
        <groupId>org.jetbrains.kotlin</groupId>
        <version>${kotlin.version}</version>

        <executions>
          <execution>
            <id>compile</id>
            <phase>process-sources</phase>
            <goals> <goal>compile</goal> </goals>
          </execution>

          <execution>
            <id>test-compile</id>
            <phase>process-test-sources</phase>
            <goals> <goal>test-compile</goal> </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.jetbrains.teamcity</groupId>
        <artifactId>teamcity-sdk-maven-plugin</artifactId>
        <version>0.1</version>
        <configuration>
          
        </configuration>
      </plugin>
    </plugins>
  </build>
  <modules>
    <module>caches-cleanup-plugin-server</module>
    <module>caches-cleanup-plugin-agent</module>
    <module>caches-cleanup-plugin-common</module>
    <module>build</module>
  </modules>
</project>

**Comment by nskvortsov** [comment]
Hi,
Thank you for the report.

Adapting a build to TeamCity 10.0 does not need a pom modificatoin. Addidng a command line option `-Dteamcity-version=10.0.5` is sufficient.

I have set up CI builds for both, 9.0 and 10.0 branches. You can see them [here](https://teamcity.jetbrains.com/project.html?projectId=TeamCityPluginsByJetBrains_CachesCleanupPlugin&guest=1)
