### ISSUE TITLE
Clean based on space requirements across multiple drives?

### ISSUE THREAD

**Issue by wbagdon** [JetBrains/teamcity-caches-cleanup-plugin#4]
Is it possible to use this plugin to clean up multiple drives on Windows agents?
Our use case is that we have an "OS" drive and an "Agent" drive C: and D: respectively.
It appears that the plugin is only triggered when the D: drive needs free space cleared but not for C:.
We have caches from NuGet, Conda, npm, etc. filling up on the C: drive but the agent is unaware of this since it is located on the D: drive.
Is this something that would need to fundamentally change in the agent code or can it be added in this plugin?

**Comment by nskvortsov** [comment]
TeamCity agent only watches the space on drives where agent's directories are located.
For example, one could configure `tmpDir` to be located at `C:\buildAgent_Tmp`  (see [documentation](https://confluence.jetbrains.com/display/TCD18/Build+Agent+Configuration)). This will trigger space clean up procedures (and caches clean up plugin) when running low on disk space on `C:`

Will this help?

**Comment by wbagdon** [comment]
This works great
